server:
  port: 10001
spring:
  application:
    name: zuulApplication
  redis:
    host: localhost
    port: 6379

fallback:
  tip: "{status: 500, message: system is error !}"
zuul:
  add-proxy-headers: true
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000
    ignoredServices: '*'
  routes:
    users:
      path: /user/**
      service-id: userApplication
    login:
      path: /login/**
      service-id: loginApplication
  sensitive-headers: "*"

# 网关熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

# Eureka注册
eureka:
  username: 123qwe
  password: 123qwe
  host: 127.0.0.1
  port: 8761
  client:
    service-url:
      defaultZone:
        http://${eureka.username}:${eureka.password}@${eureka.host}:${eureka.port}/eureka/
#  展示IP
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enable: false
  readTimeout: 60000
  connectTimeout: 60000
